language: node_js
node_js:
  - "8"
  - "9"

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - jq
      - shellcheck
      - moreutils

cache:
  directories:
    - node_modules

before_install:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew cleanup; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew cask cleanup; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install jq; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install moreutils; fi
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then brew install shellcheck; fi

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - ./script/safe-test.sh

after_success:
  - if [ "$TRAVIS_OS_NAME" == 'osx' ]; then npm run coverage; fi

stages:
  - test
  - pack
  - name: deploy
    if: branch =~ ^(master|v\d+\.\d+)

jobs:
  include:
    - stage: pack
      script:
        - npm run test:pack && echo 'Npm packing test is passed'

    - stage: deploy
      script:
        - echo "Deploying to NPM ..."
        - npm version
        - npm run dist

      deploy:
        provider: npm
        email: zixia@zixia.net
        api_key: "$NPM_TOKEN"
        skip_cleanup: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/41a19fbf1d54a04e5217
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
  email:
    on_success: change
    on_failure: change
