version: 2

jobs:
  test:
    parallelism: 1
    docker:
      - image: scholzj/circleci-centos-golang

    steps:
      - checkout
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          name: Install Node.js
          command: |
            curl --silent --location https://rpm.nodesource.com/setup_12.x | sudo bash -
            sudo yum -y install nodejs

      - run:
          name: Install RedHat Packages
          command: |
            sudo yum -y install gcc-c++ make redhat-lsb libtool autoconf
            sudo rpm -e --nodeps automake
            cd /tmp
            wget http://ftp.gnu.org/gnu/automake/automake-1.14.tar.gz
            tar xvzf automake-1.14.tar.gz
            cd automake-1.14
            ./configure --prefix=/usr
            make
            sudo make install


      - run:
          name: NPM Install
          command: npm install

      - run:
          name: Unit Testing
          command: npm run test:unit

      - run:
          name: Show CentOS Version
          command: lsb_release -a

workflows:
  version: 2
  test-flow:
    jobs:
      - test
