name: Docker

on: [push, pull_request]
#   push:
#     branches:
#       - master
#       - 'v[0-9]+*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zbeekman/ShellCheck-Linter-Action@v1.0.1
      - name: Install Bats
        run: |
          curl -sSL -o /tmp/bats_v0.4.0.tar.gz https://github.com/sstephenson/bats/archive/v0.4.0.tar.gz
          tar -xf /tmp/bats_v0.4.0.tar.gz
          sudo bats-0.4.0/install.sh /usr/local
      - run: ./scripts/docker.sh build
      - run: ./scripts/docker.sh test

  # https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions
  publish:
    name: Publish
    needs: [build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/v'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: ./scripts/docker.sh build
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PERSONAL_ACCESS_TOKEN }} | docker login -u zixia --password-stdin
      - name: Deploy to Docker Hub
        run: ./scripts/docker.sh deploy
